afc_running_platform_homepage:
    path:     /
    defaults: { _controller: AFCRunningPlatformBundle:Default:index }

afc_running_platform_admin:
    path:     /admin
    defaults: { _controller: AFCRunningPlatformBundle:Admin:index }

test_vues:
    path: /test
    defaults: { _controller: AFCRunningPlatformBundle:Default:testView }

afc_defis:
    path:    /defis
    defaults: { _controller: AFCRunningPlatformBundle:Defis:index }

creer_defis:
    path:    /defis/creerdefis
    defaults: { _controller: AFCRunningPlatformBundle:Defis:addDefis}

afficher_defis:
    path:    /defis/afficherdefis
    defaults: { _controller: AFCRunningPlatformBundle:Defis:afficherDefis}

profil_user:
    path: /profile/user/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Profile:showUser }

profil_user_stats:
    path: /profile/user/{id}/stats
    defaults: { _controller: AFCRunningPlatformBundle:Profile:showUserStats }

profil_stats:
    path:   /stats
    defaults: { _controller: AFCRunningPlatformBundle:Profile:showStats }

social_show:
    path: /social
    defaults: { _controller: AFCRunningPlatformBundle:Social:index }

social_amis:
    path: /social/amis
    defaults: { _controller: AFCRunningPlatformBundle:Social:amis }

social_ask_amis:
    path: /social/askAmis/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:askAmis }

social_cancel_amis:
    path: /social/cancelAmis/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:cancelAmis }

social_deny_amis:
    path: /social/denyAmis/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:denyAmis }

social_add_amis:
    path: /social/addAmis/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:addAmis }

social_rm_amis:
    path: /social/rmAmis/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:removeAmis }

social_groupes:
    path: /social/groupes
    defaults: { _controller: AFCRunningPlatformBundle:Social:groupes }

social_groupe_create:
    path: /social/groupes/create
    defaults: { _controller: AFCRunningPlatformBundle:Social:groupeCreate }

social_groupe_join:
    path: /social/groupes/join/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:joinGroupe }

social_groupe_quit:
    path: /social/groupes/quit/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:quitGroupe }

social_groupe_show:
    path: /social/groupes/show/{id}
    defaults: { _controller: AFCRunningPlatformBundle:Social:showGroupe }

social_groupe_challenge:
    path: /social/groupes/challenge/{idGroupe}/{idDefi}/{idUser}
    defaults: { _controller: AFCRunningPlatformBundle:Social:lancerDefis }

afc_admin_gdefiAction:
    path: /admin/gdefi/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gdefi }

afc_admin_gentrainement:
    path: /admin/gentrainement/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gentrainement }

afc_admin_gConstantes:
    path: /admin/gconstante/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gconstante }

afc_admin_gSports:
    path: /admin/gsport/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gsport }

afc_admin_gProgramme:
    path: /admin/gprogramme/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gprogramme }

afc_admin_gStatistique:
    path: /admin/gstatistique/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gstatistique }

afc_admin_gParcours:
    path: /admin/gparcours/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gparcours }

afc_admin_gUser:
    path: /admin/gmember/{action}
    defaults: { _controller: AFCRunningPlatformBundle:Admin:gmember }
