afc_running_platform_homepage:
    path:     /
    defaults: { _controller: AFCRunningPlatformBundle:Default:index }

afc_running_platform_admin:
    path:     /admin
    defaults: { _controller: AFCRunningPlatformBundle:Admin:index }

test_vues:
    path: /test
    defaults: { _controller: AFCRunningPlatformBundle:Default:testView }
    
afc_defis:
    path:    /defis
    defaults: { _controller: AFCRunningPlatformBundle:Defis:index }
    
creer_defis:
    path:    /defis/creerdefis
    defaults: { _controller: AFCRunningPlatformBundle:Defis:addDefis}

afficher_defis:
    path:    /defis/afficherdefis
    defaults: { _controller: AFCRunningPlatformBundle:Defis:afficherDefis}
